-- GRANTS FACEBOOK

    -- NATIVE APP
    
USE ROLE ACCOUNTADMIN;
GRANT USAGE ON DATABASE FIVETRAN_DATABASE TO APPLICATION DEMO_UNIFIED_MARKETING_MODEL;
GRANT USAGE ON SCHEMA FIVETRAN_DATABASE.FACEBOOK_RAW TO APPLICATION DEMO_UNIFIED_MARKETING_MODEL;
GRANT SELECT ON ALL TABLES IN SCHEMA FIVETRAN_DATABASE.FACEBOOK_RAW TO APPLICATION DEMO_UNIFIED_MARKETING_MODEL;
    -- LOCAL
    
USE ROLE ACCOUNTADMIN;
GRANT USAGE ON DATABASE FIVETRAN_DATABASE TO ROLE DATA_HARMONIZATION_DEV;
GRANT USAGE ON SCHEMA FIVETRAN_DATABASE.FACEBOOK_RAW TO ROLE DATA_HARMONIZATION_DEV;
GRANT SELECT ON ALL TABLES IN SCHEMA FIVETRAN_DATABASE.FACEBOOK_RAW TO ROLE DATA_HARMONIZATION_DEV;
-- GRANTS LINKEDIN

    -- NATIVE APP
USE ROLE ACCOUNTADMIN;
GRANT USAGE ON DATABASE OMNATA_SHARED_COPY TO APPLICATION DEMO_UNIFIED_MARKETING_MODEL;
GRANT USAGE ON SCHEMA OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW TO APPLICATION DEMO_UNIFIED_MARKETING_MODEL;
GRANT SELECT ON ALL TABLES IN SCHEMA OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW TO APPLICATION DEMO_UNIFIED_MARKETING_MODEL;

    -- LOCAL

USE ROLE ACCOUNTADMIN;
GRANT USAGE ON DATABASE OMNATA_SHARED_COPY TO ROLE DATA_HARMONIZATION_DEV;
GRANT USAGE ON SCHEMA OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW TO ROLE DATA_HARMONIZATION_DEV;
GRANT SELECT ON ALL TABLES IN SCHEMA OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW TO ROLE DATA_HARMONIZATION_DEV;
------------------------------------------------------------------------------------------------------------------------------------------

-- ENABLE CHANGE TRACKING
    --LINKEDIN
USE ROLE ACCOUNTADMIN;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."accounts" SET CHANGE_TRACKING = TRUE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_account_daily" SET CHANGE_TRACKING = TRUE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_campaign_daily" SET CHANGE_TRACKING = TRUE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_campaign_group_daily" SET CHANGE_TRACKING = TRUE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_company_daily" SET CHANGE_TRACKING = TRUE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_conversion_daily" SET CHANGE_TRACKING = TRUE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_creative_daily" SET CHANGE_TRACKING = TRUE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_impression_device_type_daily" SET CHANGE_TRACKING = TRUE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_member_company_daily" SET CHANGE_TRACKING = TRUE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_member_company_size_daily" SET CHANGE_TRACKING = TRUE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_member_country_daily" SET CHANGE_TRACKING = TRUE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_member_industry_daily" SET CHANGE_TRACKING = TRUE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_member_job_function_daily" SET CHANGE_TRACKING = TRUE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_member_job_title_daily" SET CHANGE_TRACKING = TRUE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_member_region_daily" SET CHANGE_TRACKING = TRUE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_member_seniority_daily" SET CHANGE_TRACKING = TRUE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_serving_location_daily" SET CHANGE_TRACKING = TRUE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."campaigns" SET CHANGE_TRACKING = TRUE;

    --FACEBOOK
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACCOUNT_HISTORY SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_CANVAS_COMPONENT SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_CANVAS_COMPONENT_OUTBOUND_CLICKS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_CAROUSEL_CARD SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_CONVERSION_DEVICE SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_CONVERSION_DEVICE_OUTBOUND_CLICKS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_REACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_REACTIONS_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_SOUND SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_SOUND_VIDEO_P_100_WATCHED_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_SOUND_VIDEO_P_25_WATCHED_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_SOUND_VIDEO_P_50_WATCHED_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_SOUND_VIDEO_P_75_WATCHED_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_VIEW_TYPE SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_VIEW_TYPE_VIDEO_30_SEC_WATCHED_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_VIEW_TYPE_VIDEO_AVG_TIME_WATCHED_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_VIEW_TYPE_VIDEO_P_100_WATCHED_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_VIEW_TYPE_VIDEO_P_25_WATCHED_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_VIEW_TYPE_VIDEO_P_50_WATCHED_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_VIEW_TYPE_VIDEO_P_75_WATCHED_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_VIEW_TYPE_VIDEO_THRUPLAY_WATCHED_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.AD_HISTORY SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.AD_IMAGE_HISTORY SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.AD_SET_ATTRIBUTION SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.AD_SET_HISTORY SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.AD_TRACKING SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.AD_VIDEO_HISTORY SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.AD_VIDEO_THUMBNAIL SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_AD SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_AD_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_AD_COST_PER_ACTION_TYPE SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_AD_SET SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_AD_SET_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_AD_SET_COST_PER_ACTION_TYPE SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_ALL_LEVELS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_ALL_LEVELS_COST_PER_ACTION_TYPE SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_CAMPAIGN SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_CAMPAIGN_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_CAMPAIGN_COST_PER_ACTION_TYPE SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.CAMPAIGN_HISTORY SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.CREATIVE_HISTORY SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_DEVICE SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_DEVICE_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_DEVICE_COST_PER_ACTION_TYPE SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_PLATFORM SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_PLATFORM_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_PLATFORM_AND_DEVICE SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_PLATFORM_AND_DEVICE_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_PLATFORM_AND_DEVICE_COST_PER_ACTION_TYPE SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_PLATFORM_COST_PER_ACTION_TYPE SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_PURCHASE_ROAS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_PURCHASE_ROAS_OUTBOUND_CLICKS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_AGE SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_AGE_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_AGE_AND_GENDER SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_AGE_AND_GENDER_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_AGE_AND_GENDER_COST_PER_ACTION_TYPE SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_AGE_COST_PER_ACTION_TYPE SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_COUNTRY SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_COUNTRY_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_COUNTRY_COST_PER_ACTION_TYPE SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_DMA_REGION SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_DMA_REGION_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_DMA_REGION_COST_PER_ACTION_TYPE SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_GENDER SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_GENDER_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_GENDER_COST_PER_ACTION_TYPE SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_REGION SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_REGION_ACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_REGION_COST_PER_ACTION_TYPE SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.REACH_FREQUENCY SET CHANGE_TRACKING = TRUE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.TARGETING_OPTIMIZATION_TYPES SET CHANGE_TRACKING = TRUE;

                                            --CLEAN UP
-----------------------------------------------------------------------------------------------------------------------------------------------------

-- DROP TABLES
DROP TABLE IF EXISTS DEMO_UNIFIED_MARKETING_MODEL.AGGREGATED_REPORTS.ACCOUNT_REPORT_MODEL;
DROP TABLE IF EXISTS DEMO_UNIFIED_MARKETING_MODEL.AGGREGATED_REPORTS.AD_GROUP_REPORT_MODEL;
DROP TABLE IF EXISTS DEMO_UNIFIED_MARKETING_MODEL.AGGREGATED_REPORTS.CAMPAIGN_PERFORMANCE;
DROP TABLE IF EXISTS DEMO_UNIFIED_MARKETING_MODEL.AGGREGATED_REPORTS.CAMPAIGN_REPORT_MODEL;
DROP TABLE IF EXISTS DEMO_UNIFIED_MARKETING_MODEL.AGGREGATED_REPORTS.PLATFORM_REPORT_MODEL;

DROP TABLE IF EXISTS DEMO_UNIFIED_MARKETING_MODEL.STANDARDIZE_MODEL.FACEBOOK_DIM_ACCOUNT;
DROP TABLE IF EXISTS DEMO_UNIFIED_MARKETING_MODEL.STANDARDIZE_MODEL.FACEBOOK_DIM_AD_GROUP;
DROP TABLE IF EXISTS DEMO_UNIFIED_MARKETING_MODEL.STANDARDIZE_MODEL.FACEBOOK_DIM_CAMPAIGN;
DROP TABLE IF EXISTS DEMO_UNIFIED_MARKETING_MODEL.STANDARDIZE_MODEL.FACEBOOK_METRICS;
DROP TABLE IF EXISTS DEMO_UNIFIED_MARKETING_MODEL.STANDARDIZE_MODEL.LINKEDIN_DIM_ACCOUNT;
DROP TABLE IF EXISTS DEMO_UNIFIED_MARKETING_MODEL.STANDARDIZE_MODEL.LINKEDIN_DIM_AD_GROUP;
DROP TABLE IF EXISTS DEMO_UNIFIED_MARKETING_MODEL.STANDARDIZE_MODEL.LINKEDIN_DIM_CAMPAIGN;
DROP TABLE IF EXISTS DEMO_UNIFIED_MARKETING_MODEL.STANDARDIZE_MODEL.LINKEDIN_METRICS;

DROP TABLE IF EXISTS DEMO_UNIFIED_MARKETING_MODEL.CAMPAIGN_INTELLIGENCE_COMBINED.DIM_ACCOUNT;
DROP TABLE IF EXISTS DEMO_UNIFIED_MARKETING_MODEL.CAMPAIGN_INTELLIGENCE_COMBINED.DIM_AD_GROUP;
DROP TABLE IF EXISTS DEMO_UNIFIED_MARKETING_MODEL.CAMPAIGN_INTELLIGENCE_COMBINED.DIM_CAMPAIGN;
DROP TABLE IF EXISTS DEMO_UNIFIED_MARKETING_MODEL.CAMPAIGN_INTELLIGENCE_COMBINED.METRICS;

-- REVOKE GRANTS 
    --LINKEDIN

USE ROLE ACCOUNTADMIN;
REVOKE USAGE ON DATABASE IDENTIFIER('"OMNATA_SHARED_COPY"') FROM ROLE IDENTIFIER('"DATA_HARMONIZATION_DEV"') CASCADE;
REVOKE USAGE ON SCHEMA IDENTIFIER('"OMNATA_SHARED_COPY"."LINKEDIN_ADS_RAW"') FROM ROLE IDENTIFIER('"DATA_HARMONIZATION_DEV"') CASCADE;
REVOKE SELECT ON ALL TABLES IN SCHEMA IDENTIFIER('"OMNATA_SHARED_COPY"."LINKEDIN_ADS_RAW"') FROM ROLE IDENTIFIER('"DATA_HARMONIZATION_DEV"');
    --FACEBOOK

USE ROLE ACCOUNTADMIN;
REVOKE USAGE ON DATABASE IDENTIFIER('"FIVETRAN_DATABASE"') FROM ROLE IDENTIFIER('"DATA_HARMONIZATION_DEV"') CASCADE;
REVOKE USAGE ON SCHEMA IDENTIFIER('"FIVETRAN_DATABASE"."FACEBOOK_RAW"') FROM ROLE IDENTIFIER('"DATA_HARMONIZATION_DEV"') CASCADE;
REVOKE SELECT ON ALL TABLES IN SCHEMA IDENTIFIER('"FIVETRAN_DATABASE"."FACEBOOK_RAW"') FROM ROLE IDENTIFIER('"DATA_HARMONIZATION_DEV"');

-- DISABLE CHANGE TRACKING
    -- FACEBOOK
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACCOUNT_HISTORY
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_CANVAS_COMPONENT
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_CANVAS_COMPONENT_OUTBOUND_CLICKS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_CANVAS_COMPONENT_OUTBOUND_CLICKS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_CAROUSEL_CARD
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_CONVERSION_DEVICE
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_CONVERSION_DEVICE_OUTBOUND_CLICKS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_REACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_REACTIONS_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_SOUND
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_SOUND_VIDEO_P_100_WATCHED_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_SOUND_VIDEO_P_25_WATCHED_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_SOUND_VIDEO_P_50_WATCHED_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_SOUND_VIDEO_P_75_WATCHED_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_VIEW_TYPE
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_VIEW_TYPE_VIDEO_30_SEC_WATCHED_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_VIEW_TYPE_VIDEO_AVG_TIME_WATCHED_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_VIEW_TYPE_VIDEO_P_100_WATCHED_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_VIEW_TYPE_VIDEO_P_25_WATCHED_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_VIEW_TYPE_VIDEO_P_50_WATCHED_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_VIEW_TYPE_VIDEO_P_75_WATCHED_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.ACTION_VIDEO_VIEW_TYPE_VIDEO_THRUPLAY_WATCHED_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.AD_HISTORY
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.AD_IMAGE_HISTORY
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.AD_SET_ATTRIBUTION
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.AD_SET_HISTORY
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.AD_TRACKING
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.AD_VIDEO_HISTORY
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.AD_VIDEO_THUMBNAIL
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_AD
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_AD_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_AD_COST_PER_ACTION_TYPE
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_AD_SET
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_AD_SET_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_AD_SET_COST_PER_ACTION_TYPE
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_ALL_LEVELS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_ALL_LEVELS_COST_PER_ACTION_TYPE
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_CAMPAIGN
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_CAMPAIGN_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_CAMPAIGN_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.BASIC_CAMPAIGN_COST_PER_ACTION_TYPE
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.CAMPAIGN_HISTORY
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.CREATIVE_HISTORY
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_DEVICE
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_DEVICE_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_DEVICE_COST_PER_ACTION_TYPE
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_PLATFORM
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_PLATFORM_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_PLATFORM_AND_DEVICE
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_PLATFORM_AND_DEVICE_COST_PER_ACTION_TYPE
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_PLATFORM_COST_PER_ACTION_TYPE
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_PURCHASE_ROAS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_PURCHASE_ROAS_OUTBOUND_CLICKS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_AGE
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_AGE_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_AGE_AND_GENDER
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_AGE_AND_GENDER_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_AGE_AND_GENDER_COST_PER_ACTION_TYPE
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_AGE_COST_PER_ACTION_TYPE
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_COUNTRY
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_COUNTRY_COST_PER_ACTION_TYPE
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_DMA_REGION
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_DMA_REGION_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_DMA_REGION_COST_PER_ACTION_TYPE
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_GENDER
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_GENDER_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_GENDER_COST_PER_ACTION_TYPE
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_REGION
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_REGION_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_REGION_COST_PER_ACTION_TYPE
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.REACH_FREQUENCY
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.TARGETING_OPTIMIZATION_TYPES
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DELIVERY_PLATFORM_AND_DEVICE_ACTIONS
SET CHANGE_TRACKING = FALSE;
ALTER TABLE FIVETRAN_DATABASE.FACEBOOK_RAW.DEMOGRAPHICS_COUNTRY_ACTIONS
SET CHANGE_TRACKING = FALSE;
    --LINKEDIN
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."accounts"
SET CHANGE_TRACKING = FALSE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_account_daily"
SET CHANGE_TRACKING = FALSE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_campaign_daily"
SET CHANGE_TRACKING = FALSE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_campaign_group_daily"
SET CHANGE_TRACKING = FALSE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_company_daily"
SET CHANGE_TRACKING = FALSE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_conversion_daily"
SET CHANGE_TRACKING = FALSE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_creative_daily"
SET CHANGE_TRACKING = FALSE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_impression_device_type_daily"
SET CHANGE_TRACKING = FALSE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_member_company_daily"
SET CHANGE_TRACKING = FALSE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_member_company_size_daily"
SET CHANGE_TRACKING = FALSE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_member_country_daily"
SET CHANGE_TRACKING = FALSE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_member_industry_daily"
SET CHANGE_TRACKING = FALSE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_member_job_function_daily"
SET CHANGE_TRACKING = FALSE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_member_job_title_daily"
SET CHANGE_TRACKING = FALSE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_member_region_daily"
SET CHANGE_TRACKING = FALSE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_member_seniority_daily"
SET CHANGE_TRACKING = FALSE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."ad_analytics_by_serving_location_daily"
SET CHANGE_TRACKING = FALSE;
ALTER TABLE OMNATA_SHARED_COPY.LINKEDIN_ADS_RAW."campaigns"
SET CHANGE_TRACKING = FALSE;


TRUNCATE TABLE DEMO_UNIFIED_MARKETING_MODEL.USER_SETTINGS.EXISTING_SOURCES;