from services.app import Application


# DATABASE
CONFIGURATION_SCHEMA = "CONFIGURATION"
APPLICATION = Application().app_name
USER_SETTINGS_SCHEMA = "USER_SETTINGS"
UNIFIED_MODEL_SCHEMA = "CAMPAIGN_INTELLIGENCE_COMBINED"
INFORMATION_SCHEMA = "INFORMATION_SCHEMA"
APPLICATION_KEY = "APPLICATION"


# TABLES
QUERY_TEMPLATES_TABLE = "QUERY_TEMPLATES"
DYNAMIC_TABLES_DEFINITION_TABLE = "DYNAMIC_TABLES_DEFINITION"
CONNECTOR_PROVIDERS_TABLE = "CONNECTOR_PROVIDERS"
CONNECTORS_TABLE = "CONNECTORS"
PROVIDERS_TABLE = "PROVIDERS"
EXISTING_SOURCES_TABLE = "EXISTING_SOURCES"
CAMPAIGN_PERFORMANCE_TABLE = 'CAMPAIGN_PERFORMANCE'
TABLES_TABLE = "TABLES"
TEMP_TABLE = "TEMP_TABLE"



# COLUMNS 
DATE_COLUMN = 'DATE'
MONTH_COLUMN = "MONTH"
YEAR_COLUMN = "YEAR"
MONTH_YEAR_COLUMN = "MONTH-YEAR"
CLICKS_COLUMN = 'CLICKS'
SPEND_COLUMN = "SPEND"
SORT_DATE_COLUMN = "SORT_DATE"
SPEND_PER_CLICKS_COLUMN = 'SPEND_PER_CLICKS'
FACEBOOK_ADS_COLUMN = 'FACEBOOK'
LINKEDIN_ADS_COLUMN = 'LINKEDIN'
YEAR_DATA_COLUMN = 'YEAR_DATA'
SNOW_COMP_COLUMN = 'SNOWFLAKE_PRODUCT_DEMO_ACCOUNT'
OMNATA_OLD = 'OMNATA_OLD'
OMNATA = 'OMNATA'
TABLE_SCHEMA_COLUMN = "TABLE_SCHEMA"

# KEYS 
SELECTED_MODEL_KEY = "selected_model"
CONNECTOR_KEY = "CONNECTOR"
AGGREGATED_KEY = "AGGREGATED_REPORTS_VIEWS"
AGGREGATED_REPORTS_KEY = "AGGREGATED_REPORTS"
HEADER_KEY ="HEADER_DYNAMIC_TABLE"
DATABASE_KEY = "DATABASE"
SCHEMA_KEY = "SCHEMA"
CREATED_DATE_KEY = "CREATED_DATE"
TABLE_NAME_KEY = "TABLE_NAME"
COLUMN_NAME_KEY = "COLUMN_NAME"
SOURCE_QUERIES_KEY = "source_queries"
IS_BOLD_KEY = "IS_BOLD"
CONNECTOR_ID_KEY = "CONNECTOR_ID"
PROVIDER_ID_KEY = "PROVIDER_ID"
CONNECTOR_URL_KEY= "CONNECTOR_URL"
DEFAULT_SCHEMA_KEY ="DEFAULT_SCHEMA"
COLUMNS_DEFINITION_KEY = "COLUMNS_DEFINITION"
ID_KEY = "ID"
NAME_KEY = "NAME"
QUOTED_NAME_KEY = '"name"'
TEXT_KEY = "TEXT"
IMAGE_KEY = "IMAGE"
PAGE_INFO_KEY = "page_info"
PARAMS_KEY = "params"
PROVIDER_NAME_KEY = "PROVIDER_NAME"
PROVIDER_IMAGE_KEY = "PROVIDER_IMAGE"
CONNECTOR_NAME_KEY = "CONNECTOR_NAME"
CONNECTOR_IMAGE_KEY = "CONNECTOR_IMAGE"
DATABASE_NAME_KEY= "DATABASE_NAME"
SCHEMA_NAME_KEY = "SCHEMA_NAME"
COLUMNS_KEY = "COLUMNS"
SUBSTEPS_PARAM_KEY = 'SUBSTEPS_PARAM'
PROVIDER_INFO_PARAM_KEY = 'PROVIDER_INFO_PARAM'
DATA_MODE_KEY = 'DATA_MODE'
ADD_MODE_KEY = 'ADD_MODE'
EDIT_MODE_KEY = 'EDIT_MODE'
MD_CONTENT_PARAM_KEY = 'MD_CONTENT_PARAM'
CONNECTOR_URL_PARAM_KEY = 'CONNECTOR_URL_PARAM'
GRANTED_TABLES_KEY = "GRANTED_TABLES"
USER_SELECTIONS_KEY = "USER_SELECTIONS"
MODEL_INFORMATION_KEY = "MODEL_INFORMATION"
DYNAMIC_TABLE_KEY = "DYNAMIC_TABLE"
DISABLED_TAB_KEY = "ENABLED_TAB"
LINK_DATA_TAB_ID = 0
CUSTOMIZE_MAPPINGS_TAB_ID = 1
STANDARDIZE_MODEL_KEY = "STANDARDIZE_MODEL"
ERROR_MESSAGE_KEY = "ERROR_MESSAGE"
CREATE_DYNAMIC_TABLE_KEY = "CREATE_DYNAMIC_TABLE"
SHOW_TABLES_KEY = "SHOW_TABLES"
TAG_KEY = "TAGGING_COMMENT"
GRANTER_KEY = "GRANTER"
ASSISTANT_PAGE_KEY = "ASSISTANT_PAGE"
SELECT_ASSISTANT_PAGE_KEY = "SELECT_ASSISTANT_PAGE"
ADD_ASSISTANT_PAGE_KEY = "ADD_ASSISTANT_PAGE"
CAMPAIGN_MANAGEMENT_ASSISTANT_KEY = "CAMPAIGN_MANAGEMENT_ASSISTANT"
DATA_ENGINEERING_ASSISTANT_KEY = "DATA_ENGINEERING_ASSISTANT"
SELECTED_CHAT_KEY = "SELECTED_CHAT"
EDITING_ASSISTANT_KEY = "EDITING_ASSISTANT"
MDEA_KEY = "MDEA"
MCMA_KEY = "MCMA"

# LINK TO DATA KEYS
LINK_TO_DATA_KEY = "LINK_TO_DATA"
LAST_STATE_KEY = "LAST_STATE"
LINK_TO_YOUR_DATA_STATE_KEY = "LINK_TO_YOUR_DATA_STATE"
SELECT_CONNECTOR_STATE_KEY = "SELECT_CONNECTOR_STATE"
CONNECTOR_SETUP_STATE_KEY = "CONNECTOR_SETUP_STATE"
DATA_ALREADY_IN_SNOWFLAKE_STATE_KEY = "DATA_ALREADY_IN_SNOWFLAKE_STATE"

# COLORS
WHITE = '#FFFFFF'
LIGHT_GRAY_1 = '#F0F2F6'
LIGHT_GRAY_2 = '#E6EAF1'
LIGHT_GRAY_3 = '#C4D0CB'
DARK_GRAY_1 = '#555867'
DARK_GRAY_2 = '#3E4250'
DARK_GRAY_3 = '#2F333D'
BLACK = '#000000'


# CHARACTERS
NEW_LINE = "\n"

#CHATBOT
# SCHEMAS
LLM_SCHEMA = "LLM"
LLM_SEMANTIC_MODEL_STAGE = "SEMANTIC_MODEL"
LLM_CONFIGURATION_STAGE = "CONFIGURATION"
LLM_CONFIGURATION_FILE = "assistant_config.yaml"

API = "mobilize.snowflakecomputing.com"
TAG = '\'{"origin":"sf_sit","name":"Marketing Data Foundation","version":{"major":0, "minor":1},"attributes":""}\''

# TABLES
ASSISTANT_TABLE = "ASSISTANT"
ASSISTANT_TABLE_ID_COL = "ID"
ASSISTANT_TABLE_NAME_COL = "NAME"
ASSISTANT_TABLE_TYPE_COL = "ASSISTANT"
ASSISTANT_TABLE_SYS_PROMPT_COL = "SYS_PROMPT"
ASSISTANT_TABLE_CHAT_COL = "CHAT"
ASSISTANT_TABLE_USER_COL = "USER"


# URLS
CHANGE_TRACKING_DOCUMENTATION = "https://docs.snowflake.com/en/user-guide/dynamic-tables-tasks-create#enable-change-tracking"


# COMMANDS
USE_ADMIN_ROLE_COMMAND = "USE ROLE <ACCOUNTADMIN>;"